package marsvinet;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author caspe
 */
public class GUI extends javax.swing.JFrame {

    DBConnector c = null;
    DAO data = null;
    Controller logic = null;

    public GUI() {
        try {
            
            c = new DBConnector();
            data = new DAO(c);
            logic = new Controller();

            initComponents();
            fillListEliteSenior();
            fillListAllMembers();
            jTabbedPane1.remove(jPanelHidden);
            jTabbedPane1.remove(jPanelNewMember);
            jPanelMembers.remove(jButtonLogout);

        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMembers = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMembers = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMembers = new javax.swing.JTextArea();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldPassWord = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelNewMember = new javax.swing.JPanel();
        newMemberName = new javax.swing.JTextField();
        newMemberBirthday = new javax.swing.JTextField();
        newMemberActive = new javax.swing.JRadioButton();
        newMemberElite = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        eliteSenior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEliteSenior = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelHidden = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListMembers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMembersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListMembers);

        jTextAreaMembers.setEditable(false);
        jTextAreaMembers.setColumns(20);
        jTextAreaMembers.setRows(5);
        jScrollPane4.setViewportView(jTextAreaMembers);

        jTextFieldUserName.setText("admin");

        jTextFieldPassWord.setText("1233");

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMembersLayout = new javax.swing.GroupLayout(jPanelMembers);
        jPanelMembers.setLayout(jPanelMembersLayout);
        jPanelMembersLayout.setHorizontalGroup(
            jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMembersLayout.createSequentialGroup()
                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLogin))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanelMembersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldPassWord, jTextFieldUserName});

        jPanelMembersLayout.setVerticalGroup(
            jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMembersLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonLogout))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Members", jPanelMembers);

        newMemberName.setText("name");

        newMemberBirthday.setText("birthday");

        newMemberActive.setSelected(true);
        newMemberActive.setText("active");

        newMemberElite.setText("elite");

        jButton1.setText("New Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewMemberLayout = new javax.swing.GroupLayout(jPanelNewMember);
        jPanelNewMember.setLayout(jPanelNewMemberLayout);
        jPanelNewMemberLayout.setHorizontalGroup(
            jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(newMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newMemberBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newMemberActive)
                .addGap(18, 18, 18)
                .addComponent(newMemberElite)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jPanelNewMemberLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newMemberBirthday, newMemberName});

        jPanelNewMemberLayout.setVerticalGroup(
            jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newMemberBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newMemberActive)
                    .addComponent(newMemberElite)
                    .addComponent(jButton1))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Member", null, jPanelNewMember, "");

        jListEliteSenior.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEliteSenior);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout eliteSeniorLayout = new javax.swing.GroupLayout(eliteSenior);
        eliteSenior.setLayout(eliteSeniorLayout);
        eliteSeniorLayout.setHorizontalGroup(
            eliteSeniorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliteSeniorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        eliteSeniorLayout.setVerticalGroup(
            eliteSeniorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliteSeniorLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(eliteSeniorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Elite Senior", eliteSenior);

        javax.swing.GroupLayout jPanelHiddenLayout = new javax.swing.GroupLayout(jPanelHidden);
        jPanelHidden.setLayout(jPanelHiddenLayout);
        jPanelHiddenLayout.setHorizontalGroup(
            jPanelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        jPanelHiddenLayout.setVerticalGroup(
            jPanelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hidden Tab", jPanelHidden);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newMemberFromGUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMembersMouseClicked
        jTextAreaMembers.setText("");
        String memberInfo = jListMembers.getSelectedValue();
        String[] bites = memberInfo.split("\\s+");
        int id = Integer.parseInt(bites[0]);
        Member member = data.getMember(id);
        jTextAreaMembers.append("Id: " + member.getId() + "\n");
        jTextAreaMembers.append("Name: " + member.getName() + "\n");
        jTextAreaMembers.append("Birthday: " + member.getBirthday() + "\n");
        jTextAreaMembers.append("Active: " + member.getActive() + "\n");
        jTextAreaMembers.append("Elite: " + member.getElite() + "\n");
        //jTextFieldMembers.setText(data.getMember(id).toString());

        //Member member = (Member)jListMembers.getSelectedValue();
    }//GEN-LAST:event_jListMembersMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String usernameInput = jTextFieldUserName.getText();
        String passwordInput = jTextFieldPassWord.getText();

        if (logic.login(usernameInput, passwordInput)) {
            jTabbedPane1.add("New Member", jPanelNewMember);
            jTabbedPane1.add("Hidden", jPanelHidden);
            jPanelMembers.remove(jTextFieldUserName);
            jPanelMembers.remove(jTextFieldPassWord);
            jPanelMembers.remove(jButtonLogin);
            jPanelMembers.add(jButtonLogout);
        } else {
            JOptionPane.showMessageDialog(this, "You shall not pass, fool..");
        }


    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        jTabbedPane1.remove(jPanelHidden);
        jTabbedPane1.remove(jPanelNewMember);
        jPanelMembers.remove(jButtonLogout);
        jPanelMembers.add(jTextFieldUserName);
        jPanelMembers.add(jTextFieldPassWord);
        jTextFieldPassWord.setText("1233");
        jPanelMembers.add(jButtonLogin);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public void newMemberFromGUI() {
        String name;
        int birthday;
        String active;
        String elite;

        name = newMemberName.getText();
        birthday = Integer.parseInt(newMemberBirthday.getText());

        if (newMemberActive.isSelected()) {
            active = "true";
        } else {
            active = "false";
        }

        if (newMemberElite.isSelected()) {
            elite = "true";
        } else {
            elite = "false";
        }

        data.newMember(name, birthday, active, elite);

        newMemberName.setText("");
        newMemberBirthday.setText("");
        newMemberElite.setSelected(false);
    }

    private void fillListEliteSenior() {
        DefaultListModel model = new DefaultListModel();

        for (Member member : data.getTeamEliteSenior()) {
            model.addElement(member);
        }

        jListEliteSenior.setModel(model);
    }

    private void fillListAllMembers() {
        DefaultListModel model = new DefaultListModel();

        for (Member member : data.getMembers()) {
            model.addElement(member.toString());
        }
        jListMembers.setModel(model);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eliteSenior;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JList<String> jListEliteSenior;
    private javax.swing.JList<String> jListMembers;
    private javax.swing.JPanel jPanelHidden;
    private javax.swing.JPanel jPanelMembers;
    public javax.swing.JPanel jPanelNewMember;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaMembers;
    private javax.swing.JTextField jTextFieldPassWord;
    private javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JRadioButton newMemberActive;
    private javax.swing.JTextField newMemberBirthday;
    private javax.swing.JRadioButton newMemberElite;
    private javax.swing.JTextField newMemberName;
    // End of variables declaration//GEN-END:variables
}
